name: Test runner
run-name: ${{ github.repository }} running test
on: [push]

jobs:
  test-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: cd ./be-todo
      - run: yarn install
      - run: yarn run test
